import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import Logo from "@/assets/images/logo.svg";
import Hero from "@/assets/images/hero.jpeg";
import CardList from "@/components/cardList";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>SeaAdventure</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.Header}>
        <Image src={Logo} />
      </header>
      <main className={styles.Main}>
        <h2>Lorem ipsum dolor sit amet</h2>
        <Image src={Hero} />
      </main>

      <section>
        <CardList />
      </section>
    </>
  );
}
